Repository danieljancar/votevault, pull requests merged in 2024-08, with the labels that each got.

#15 feat: create home and create vote component
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/config/config.ts
  apps/frontend/src/app/core/stellar/createVote.service.ts
  apps/frontend/src/app/features/home/home.component.html
  apps/frontend/src/app/features/home/home.component.ts
  apps/frontend/src/app/features/voting/create/create.component.css
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/features/voting/create/create.component.spec.ts
  apps/frontend/src/app/features/voting/create/create.component.ts
  apps/frontend/src/app/shared/error/error.component.css
  apps/frontend/src/app/shared/error/error.component.html
  apps/frontend/src/app/shared/error/error.component.spec.ts
  apps/frontend/src/app/shared/error/error.component.ts
  apps/frontend/src/app/shared/loading/loading.component.css
  apps/frontend/src/app/shared/loading/loading.component.html
  apps/frontend/src/app/shared/loading/loading.component.spec.ts
  apps/frontend/src/app/shared/loading/loading.component.ts
  apps/frontend/src/app/shared/navbar/navbar.component.html
  apps/frontend/src/app/shared/navbar/navbar.component.ts
  apps/frontend/src/app/shared/success/success.component.css
  apps/frontend/src/app/shared/success/success.component.html
  apps/frontend/src/app/shared/success/success.component.spec.ts
  apps/frontend/src/app/shared/success/success.component.ts
Labels: enhancement, DSC mandatory

#16 feat: add max 5 options and remove date
  apps/frontend/src/app/config/config.ts
  apps/frontend/src/app/core/stellar/castVote.service.ts
  apps/frontend/src/app/core/stellar/checkUserVoted.service.ts
  apps/frontend/src/app/core/stellar/getVote.service.ts
  apps/frontend/src/app/core/stellar/getVoteOption.service.ts
  apps/frontend/src/app/core/stellar/getVoteResults.service.ts
  contracts/VotingContract/src/lib.rs
  contracts/VotingContract/src/test.rs
Labels: enhancement, DSC mandatory, security

#22 feat: create stellar-based auth
  apps/frontend/src/app/app.routes.ts
  apps/frontend/src/app/config/config.ts
  apps/frontend/src/app/core/auth.service.ts
  apps/frontend/src/app/features/login/login.component.html
  apps/frontend/src/app/features/login/login.component.ts
  apps/frontend/src/app/features/register/register.component.html
  apps/frontend/src/app/features/register/register.component.ts
  apps/frontend/src/app/features/voting/cast/cast.component.ts
  apps/frontend/src/app/features/voting/create/create.component.ts
  apps/frontend/src/app/features/voting/voting.component.ts
  apps/frontend/src/app/guards/auth.guard.ts
  apps/frontend/src/app/shared/success/success.component.html
  apps/frontend/src/app/shared/success/success.component.ts
Labels: enhancement, DSC mandatory, security

#27 feat: create share link banner on succesful vote creation
  README.md
  apps/frontend/src/app/features/login/login.component.html
  apps/frontend/src/app/features/register/register.component.html
  apps/frontend/src/app/features/voting/cast/cast.component.html
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/features/voting/create/create.component.ts
  apps/frontend/src/app/features/voting/create/share/share.component.css
  apps/frontend/src/app/features/voting/create/share/share.component.html
  apps/frontend/src/app/features/voting/create/share/share.component.spec.ts
  apps/frontend/src/app/features/voting/create/share/share.component.ts
  contracts/VotingContract/src/lib.rs
Labels: enhancement, DSC mandatory

#29 feat: add text-lenght-counter and login-fix
  apps/frontend/src/app/config/config.ts
  apps/frontend/src/app/core/auth.service.ts
  apps/frontend/src/app/core/stellar/castVote.service.ts
  apps/frontend/src/app/core/stellar/createVote.service.ts
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/features/voting/create/create.component.ts
  apps/frontend/src/app/shared/navigation/navbar/navbar.component.ts
  contracts/VotingContract/src/lib.rs
  contracts/VotingContract/src/test.rs
Labels: enhancement, DSC mandatory

#31 feat: no vote data dublicate
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/features/voting/create/create.component.ts
  apps/frontend/src/app/features/voting/create/share/share.component.ts
Labels: enhancement, DSC mandatory

#46 docs: bring contract documentation up to date
  contracts/VotingContract/README.md
Labels: documentation, DSC mandatory

#41 fix: show create vote validation correctly
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/utils/create-vote-validators.util.ts
Labels: bug, DSC mandatory

#44 feat: add download button to create vote
  apps/frontend/src/app/features/voting/create/create.component.html
  apps/frontend/src/app/features/voting/create/share/share.component.html
  apps/frontend/src/app/features/voting/create/share/share.component.ts
Labels: enhancement, DSC mandatory

#43 fix: break words when too long
  apps/frontend/src/app/features/voting/cast/cast.component.html
Labels: bug, DSC mandatory

#42 fix: add loading spinner when login / logout still undefined
  apps/frontend/src/app/core/auth.service.ts
  apps/frontend/src/app/shared/navigation/navbar/navbar.component.html
  apps/frontend/src/app/shared/navigation/navbar/navbar.component.ts
Labels: bug, DSC mandatory

#66 fix: cookie not resetting after browser restart
  apps/frontend/src/app/core/auth.service.ts
Labels: bug, DSC mandatory

#68 feat: add cookie disclaimer until accepted
  apps/frontend/src/app/app.component.html
  apps/frontend/src/app/app.component.ts
  apps/frontend/src/app/features/home/home.component.spec.ts
  apps/frontend/src/app/shared/navigation/disclaimer/disclaimer.component.css
  apps/frontend/src/app/shared/navigation/disclaimer/disclaimer.component.html
  apps/frontend/src/app/shared/navigation/disclaimer/disclaimer.component.spec.ts
  apps/frontend/src/app/shared/navigation/disclaimer/disclaimer.component.ts
  package-lock.json
Labels: enhancement, DSC mandatory

#72 feat: add spec tests to frontend
  apps/frontend/src/app/app.component.spec.ts
  apps/frontend/src/app/features/home/home.component.spec.ts
  apps/frontend/src/app/features/login/login.component.spec.ts
  apps/frontend/src/app/features/register/register.component.spec.ts
  apps/frontend/src/app/features/voting/cast/cast.component.spec.ts
  apps/frontend/src/app/features/voting/create/create.component.spec.ts
  apps/frontend/src/app/features/voting/create/share/share.component.spec.ts
  apps/frontend/src/app/features/voting/results/results.component.spec.ts
  apps/frontend/src/app/features/voting/voting.component.spec.ts
  apps/frontend/src/app/shared/navigation/navbar/navbar.component.spec.ts
  apps/frontend/src/app/shared/services/confirm-reload/confirm-reload.service.spec.ts
Labels: enhancement, DSC mandatory

#73 feat: add loading spinner to login button for slow wifi feedback
  apps/frontend/src/app/features/login/login.component.html
  apps/frontend/src/app/features/login/login.component.ts
  apps/frontend/src/app/shared/feedback/button-spinner/button-spinner.component.css
  apps/frontend/src/app/shared/feedback/button-spinner/button-spinner.component.html
  apps/frontend/src/app/shared/feedback/button-spinner/button-spinner.component.spec.ts
  apps/frontend/src/app/shared/feedback/button-spinner/button-spinner.component.ts
Labels: enhancement

#74 fix: make sure no duplicates are loaded
  apps/frontend/src/app/core/stellar/getVote.service.ts
  apps/frontend/src/app/core/stellar/getVoteOption.service.ts
  apps/frontend/src/app/core/stellar/getVoteResults.service.ts
Labels: bug, DSC mandatory

#76 feat: add button spinner to register button
  apps/frontend/src/app/features/register/register.component.html
  apps/frontend/src/app/features/register/register.component.ts
  apps/frontend/src/app/shared/feedback/button-spinner/button-spinner.component.html
Labels: enhancement, DSC mandatory

#78 fix: disable register button when loading
  apps/frontend/src/app/features/register/register.component.html
Labels: bug, DSC mandatory

#80 feat: add footer to the bottom of the page
  apps/frontend/src/app/app.component.html
  apps/frontend/src/app/app.component.ts
  apps/frontend/src/app/shared/footer/footer.component.css
  apps/frontend/src/app/shared/footer/footer.component.html
  apps/frontend/src/app/shared/footer/footer.component.spec.ts
  apps/frontend/src/app/shared/footer/footer.component.ts
Labels: enhancement, DSC mandatory

#84 fix: remove unused contract packages
  packages/voting_contract/.gitignore
  packages/voting_contract/README.md
  packages/voting_contract/package-lock.json
  packages/voting_contract/package.json
  packages/voting_contract/src/index.ts
  packages/voting_contract/tsconfig.json
Labels: enhancement

#85 fix: add ActivatedRoute to spec tests
  apps/frontend/src/app/features/home/home.component.spec.ts
  apps/frontend/src/app/features/login/login.component.spec.ts
  apps/frontend/src/app/features/register/register.component.spec.ts
  apps/frontend/src/app/shared/navigation/navbar/navbar.component.spec.ts
Labels: bug, Testing
